### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by noahcgreen**
I added a few setup files so that the project could be installed to other locations, and cleaned up test.py a bit.

### CODE REVIEW

**Comment by cerule7** [comment]
Thanks man!

**Comment by cerule7** [comment]
Btw the latest push added a database -- it doesn't do anything right now, but I'm going to experiment with creating class objects vs. directly querying the database

**Comment by noahcgreen** [comment]
Sure!

If you'd like, I can reorganize the project to use a package structure like I mentioned — should make it easier to tell where to put what code.

**Comment by cerule7** [comment]
Hey Noah! 

That would be very useful.

I've added an update on the project; now it's possible to get a list of all classes with a certain core. Classes are going to be represented with objects. 

By the way, sorry for the delay in responding! I've had a lot of homework and no time to work on this haha

**Pull request merged**
